services:
  backend:
    build:
      context: ./backend
    container_name: rocketlab-backend
    environment:
      DATABASE_URL: sqlite:////data/database.db
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
    ports:
      - "8000:8000"
    volumes:
      - backend_sqlite_data:/data

  frontend:
    build:
      context: ./frontend
    container_name: rocketlab-frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  backend_sqlite_data:
